import Badge from "@/app/_components/badge";
import Table from "@/app/_components/table";
import moment from "moment";
import React, { useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { router } from "@inertiajs/react";
import ReUploadDocumentSection from "../../employees/id/201_files/_sections/re-upload-document-section";
import { update_201_files_service } from "@/app/services/human-resources-service";
import store from "@/app/store/store";
import { get_201_files_thunk } from "@/app/redux/employee-relation-thunk";

export default function FIlesTableSection({ props_data }) {
    const documents = props_data?.files;
    const { data } = useSelector((store) => store.app);
    const [loadingId, setLoadingId] = useState(null);
    const [notification, setNotification] = useState(null); // Local notification alert state

    // Get search params from URL
    const params = new URLSearchParams(typeof window !== "undefined" ? window.location.search : "");
    const search_documents = params.get("search") || "";
    const filter_status = params.get("status") || "all";

    const columns = [
        { header: "Name of Employee", accessor: "name" },
        { header: "Document Name", accessor: "documents" },
        { header: "Date Uploaded", accessor: "created_at" },
        { header: "Status", accessor: "status" },
        { header: "Open Link", accessor: "url" },
        { header: "Action", accessor: "action" },
    ];

    const getBadgeVariant = (status) => {
        switch (status) {
            case "Pending":
                return "warning";
            case "Approved":
            case "Signed":
            case "Completed":
                return "success";
            case "Re-Uploaded":
                return "secondary";
            case "Declined":
                return "danger";
            default:
                return "primary";
        }
    };

    // Extract IDs, Timestamps, and Signature
    const employeeData = data?.user?.account_employee;
    const contractId = employeeData?.is_has_contract;
    const onboardingDate = employeeData?.onboarding_agree_on;
    const signature = employeeData?.signature;

    // Prepare raw data array
    let rawList = Array.isArray(documents?.data)
        ? [...documents.data]
        : (Array.isArray(documents) ? [...documents] : []);

    // Inject Signature Row
    if (signature) {
        rawList.unshift({
            id: `signature-${data?.user?.id}`,
            name: "E-Signature File",
            status: "Completed",
            created_at: employeeData?.updated_at || employeeData?.created_at,
            isAutoGenerated: true,
            type: "signature",
            // url: `/accounts/my_profile/signature`
        });
    }

    // Inject Onboarding Agreement Row
    if (onboardingDate) {
        rawList.unshift({
            id: `onboarding-${data?.user?.id}`,
            name: "Onboarding Agreement",
            status: "Completed",
            created_at: onboardingDate,
            isAutoGenerated: true,
            type: "onboarding",
            url: `/accounts/my_documents/${data?.user?.id}/onboarding`
        });
    }

    // Inject Employment Contract Row
    if (contractId) {
        rawList.unshift({
            id: `contract-${contractId}`,
            name: "Employment Contract",
            status: "Completed",
            created_at: employeeData?.contract_signed_at || employeeData?.created_at,
            isAutoGenerated: true,
            type: "contract",
            url: `/accounts/my_documents/${data?.user?.id}/contract`
        });
    }

    // Filter documents based on search and status
    const filteredList = rawList.filter((res) => {
        const searchLower = search_documents.toLowerCase();
        const matchesSearch =
            !search_documents ||
            res.name?.toLowerCase().includes(searchLower) ||
            res.status?.toLowerCase().includes(searchLower);

        const matchesStatus =
            filter_status === "all" ||
            res.status?.toLowerCase() === filter_status.toLowerCase();

        return matchesSearch && matchesStatus;
    });

    // Compute status counts for interactive filter badges
    const statusCounts = {
        all: rawList.length,
        pending: rawList.filter(d => d.status?.toLowerCase() === "pending").length,
        completed: rawList.filter(d => ["completed", "approved", "signed"].includes(d.status?.toLowerCase())).length,
        declined: rawList.filter(d => d.status?.toLowerCase() === "declined").length,
    };

    // Helper to display user notifications
    const triggerNotification = (type, message) => {
        setNotification({ type, message });
        setTimeout(() => {
            setNotification(null);
        }, 4000);
    };

    // Handle Approve / Decline Actions
    async function handleUpdateStatus(doc, targetStatus) {
        try {
            setLoadingId(`${doc.id}-${targetStatus}`);
            await update_201_files_service({
                id: doc.id,
                status: targetStatus,
            });

            // Dispatch Redux thunk to refresh store data
            await store.dispatch(get_201_files_thunk());
            router.reload({ preserveState: true });

            // Display success notification based on status submitted
            triggerNotification(
                targetStatus === "Approved" ? "success" : "danger",
                `Document "${doc.name}" has been successfully ${targetStatus.toLowerCase()}.`
            );
        } catch (error) {
            triggerNotification("error", "Failed to update document status. Please try again.");
        } finally {
            setLoadingId(null);
        }
    }

    // Format filtered data for table display
    const formattedData = filteredList.map((res) => {
        const employeeFullName = [
            props_data?.personal_information?.first_name,
            props_data?.personal_information?.middle_name,
            props_data?.personal_information?.last_name,
        ].filter(Boolean).join(" ") || "N/A";

        const fullUrl = res.isAutoGenerated && typeof window !== "undefined"
            ? `${window.location.origin}${res.url}`
            : res.url;

        const isApproving = loadingId === `${res.id}-Approved`;
        const isDeclining = loadingId === `${res.id}-Declined`;

        return {
            ...res,
            name: employeeFullName,
            documents: res.name,
            url: res.url ? (
                <a
                    href={res.url}
                    className="underline cursor-pointer text-blue-500 break-all text-[11px] hover:text-blue-700 transition-colors"
                    target="_blank"
                    rel="noreferrer"
                >
                    {fullUrl}
                </a>
            ) : (
                <span className="text-gray-400 text-[10px] italic">No URL available</span>
            ),
            status: (
                <Badge
                    label={res.status}
                    variant={getBadgeVariant(res.status)}
                    className="rounded-md text-white font-medium px-2.5 py-1 text-[11px]"
                />
            ),
            created_at: res.created_at ? moment(res.created_at).format("LLL") : "—",
            action: res.isAutoGenerated ? (
                <span className="text-gray-400 italic text-[10px] bg-gray-100 px-2 py-0.5 rounded">
                    System Generated
                </span>
            ) : res.status === "Pending" ? (
                <div className="flex items-center gap-1.5">
                    <button
                        type="button"
                        disabled={!!loadingId}
                        onClick={() => handleUpdateStatus(res, "Approved")}
                        className="px-2.5 py-1 text-[11px] font-medium bg-emerald-50 text-emerald-600 hover:bg-emerald-600 hover:text-white rounded-md transition-all active:scale-95 disabled:opacity-50 cursor-pointer"
                    >
                        {isApproving ? "Approving..." : "Approve"}
                    </button>
                    <button
                        type="button"
                        disabled={!!loadingId}
                        onClick={() => handleUpdateStatus(res, "Declined")}
                        className="px-2.5 py-1 text-[11px] font-medium bg-rose-50 text-rose-600 hover:bg-rose-600 hover:text-white rounded-md transition-all active:scale-95 disabled:opacity-50 cursor-pointer"
                    >
                        {isDeclining ? "Declining..." : "Decline"}
                    </button>
                </div>
            ) : (
                res.status === "Declined" && (
                    <ReUploadDocumentSection data={res} />
                )
            ),
        };
    });

    // Handle interactive status filter click
    const handleStatusFilter = (statusKey) => {
        const currentParams = typeof window !== "undefined"
            ? Object.fromEntries(new URLSearchParams(window.location.search))
            : {};

        const updatedParams = {
            ...currentParams,
            status: statusKey,
            page: 1,
        };

        if (statusKey === "all") {
            delete updatedParams.status;
        }

        router.get(
            window.location.pathname,
            updatedParams,
            { preserveState: true, replace: true }
        );
    };

    // Clear filters action
    const handleClearFilters = () => {
        router.get(
            window.location.pathname,
            {},
            { preserveState: true, replace: true }
        );
    };

    const statusFilterOptions = [
        { label: "All Files", key: "all", count: statusCounts.all },
        { label: "Pending", key: "pending", count: statusCounts.pending },
        { label: "Completed / Approved", key: "completed", count: statusCounts.completed },
        { label: "Declined", key: "declined", count: statusCounts.declined },
    ];

    return (
        <div className="w-full space-y-4">
            {/* Notification Alert Banner */}
            {notification && (
                <div
                    className={`flex items-center justify-between px-4 py-3 rounded-lg text-xs font-medium border shadow-sm transition-all duration-300 ${notification.type === "success"
                            ? "bg-emerald-50 text-emerald-800 border-emerald-200"
                            : notification.type === "danger"
                                ? "bg-amber-50 text-amber-800 border-amber-200"
                                : "bg-rose-50 text-rose-800 border-rose-200"
                        }`}
                >
                    <div className="flex items-center gap-2">
                        {notification.type === "success" && (
                            <svg className="w-4 h-4 text-emerald-600 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" />
                            </svg>
                        )}
                        {notification.type === "danger" && (
                            <svg className="w-4 h-4 text-amber-600 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                            </svg>
                        )}
                        {notification.type === "error" && (
                            <svg className="w-4 h-4 text-rose-600 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        )}
                        <span>{notification.message}</span>
                    </div>
                    <button
                        type="button"
                        onClick={() => setNotification(null)}
                        className="text-gray-400 hover:text-gray-600 cursor-pointer ml-3"
                    >
                        ✕
                    </button>
                </div>
            )}

            {/* Interactive Status Filter Tabs */}
            <div className="flex flex-wrap items-center gap-2 pb-2 border-b border-gray-100">
                <span className="text-xs font-semibold text-gray-500 mr-2">Filter Status:</span>
                {statusFilterOptions.map((item) => {
                    const isActive = filter_status.toLowerCase() === item.key.toLowerCase();
                    return (
                        <button
                            key={item.key}
                            type="button"
                            onClick={() => handleStatusFilter(item.key)}
                            className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all cursor-pointer ${isActive
                                    ? "bg-blue-600 text-white shadow-sm ring-2 ring-blue-500/20"
                                    : "bg-gray-100 text-gray-600 hover:bg-gray-200 hover:text-gray-900"
                                }`}
                        >
                            <span>{item.label}</span>
                            <span
                                className={`px-1.5 py-0.2 rounded-full text-[10px] font-bold ${isActive
                                        ? "bg-white/20 text-white"
                                        : "bg-gray-200 text-gray-700"
                                    }`}
                            >
                                {item.count}
                            </span>
                        </button>
                    );
                })}
            </div>

            {/* Table or Empty State */}
            <div className="w-full overflow-x-auto">
                {formattedData.length > 0 ? (
                    <Table columns={columns} data={formattedData} />
                ) : (
                    <div className="bg-white border border-dashed border-gray-300 rounded-xl p-10 text-center flex flex-col items-center justify-center my-4 shadow-sm hover:border-blue-300 transition-all">
                        <div className="w-16 h-16 bg-blue-50 text-blue-500 rounded-full flex items-center justify-center mb-4 ring-8 ring-blue-50/50 animate-pulse">
                            <svg
                                className="w-8 h-8"
                                fill="none"
                                stroke="currentColor"
                                viewBox="0 0 24 24"
                            >
                                <path
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                    strokeWidth="1.5"
                                    d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                                />
                            </svg>
                        </div>

                        <h3 className="text-base font-semibold text-gray-800 mb-1">
                            No Documents Found
                        </h3>

                        <p className="text-sm text-gray-500 max-w-sm mb-6">
                            {search_documents || filter_status !== "all" ? (
                                <>
                                    No 201 files match status filter{" "}
                                    <span className="font-semibold text-gray-700 capitalize">"{filter_status}"</span>
                                    {search_documents && <> and search query <span className="font-semibold text-gray-700">"{search_documents}"</span></>}
                                </>
                            ) : (
                                "There are currently no 201 files or system documents uploaded for this employee record."
                            )}
                        </p>

                        {(search_documents || filter_status !== "all") && (
                            <button
                                onClick={handleClearFilters}
                                className="inline-flex items-center gap-2 px-4 py-2 text-xs font-medium text-blue-600 bg-blue-50 rounded-lg hover:bg-blue-100 transition-colors focus:ring-2 focus:ring-blue-500/20 active:scale-95 transform cursor-pointer"
                            >
                                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                                </svg>
                                Clear Active Search & Filters
                            </button>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
}