import Badge from "@/app/_components/badge";
import Table from "@/app/_components/table";
import moment from "moment";
import React from "react";
import { useSelector } from "react-redux";
import ReUploadDocumentSection from "./re-upload-document-section";

export default function TableSection() {
    const { documents } = useSelector((store) => store.applicants);
    const { data, user } = useSelector((store) => store.app);

    console.log("userzzz", user.documents);
    const columns = [
        { header: "Document Name", accessor: "name" },
        { header: "Date Uploaded", accessor: "created_at" },
        { header: "Status", accessor: "status" },
        { header: "Open Link", accessor: "url" },
        { header: "Action", accessor: "action" },
    ];

    const getBadgeVariant = (status) => {
        switch (status) {
            case "Pending":
                return "warning";
            case "Approved":
                return "success";
            case "Re-Uploaded":
                return "secondary";
            case "Declined":
                return "danger";
            case "Signed":
            case "Completed":
                return "success";
            default:
                return "primary";
        }
    };

    // 1. Extract IDs, Timestamps, and Signature
    const employeeData = data?.user?.account_employee;
    const contractId = employeeData?.is_has_contract;
    const onboardingDate = employeeData?.onboarding_agree_on;
    const signature = employeeData?.signature;

    // 2. Prepare the raw data array
    let rawList = user.documents ? [...user.documents] : [];

    // 3. Inject Signature Row
    if (signature) {
        rawList.unshift({
            id: `signature-${data?.user?.id}`,
            name: "E-Signature File",
            status: "Completed",
            created_at: employeeData?.updated_at || employeeData?.created_at,
            isAutoGenerated: true,
            type: "signature",
        });
    }

    // 4. Inject Onboarding Agreement Row
    if (onboardingDate) {
        rawList.unshift({
            id: `onboarding-${data?.user?.id}`,
            name: "Onboarding Agreement",
            status: "Completed",
            created_at: onboardingDate,
            isAutoGenerated: true,
            type: "onboarding",
        });
    }

    // 5. Inject Employment Contract Row
    if (contractId) {
        rawList.unshift({
            id: `contract-${contractId}`,
            name: "Employment Contract",
            status: "Completed",
            created_at:
                employeeData?.contract_signed_at || employeeData?.created_at,
            isAutoGenerated: true,
            type: "contract",
        });
    }

    // 6. Map the data for display
    const formattedData = rawList.map((res) => {
        let autoHref = "";
        if (res.isAutoGenerated) {
            if (res.type === "contract")
                autoHref = `/accounts/my_documents/${data?.user?.id}/contract`;
            else if (res.type === "onboarding")
                autoHref = `/accounts/my_documents/${data?.user?.id}/onboarding`;
            else if (res.type === "signature")
                autoHref = `/accounts/my_profile/signature`; // The signature is usually a direct URL/Path
        }

        return {
            ...res,
            url: res.isAutoGenerated ? (
                <a
                    href={autoHref}
                    className="underline cursor-pointer text-blue-500 break-all text-[10px]"
                    target="_blank"
                    rel="noreferrer"
                >
                    {`${window.location.origin}${autoHref}`}
                </a>
            ) : (
                <a
                    className="underline cursor-pointer text-blue-500 break-all text-[10px]"
                    href={res.url}
                    target="_blank"
                    rel="noreferrer"
                >
                    {res.url}
                </a>
            ),
            status: (
                <Badge
                    label={res.status}
                    variant={getBadgeVariant(res.status)}
                    className="rounded-md text-white"
                />
            ),
            created_at: moment(res.created_at).format("LLL"),
            action: res.isAutoGenerated ? (
                <span className="text-gray-400 italic text-[10px]">
                    System Generated
                </span>
            ) : (
                res.status === "Declined" && (
                    <ReUploadDocumentSection data={res} />
                )
            ),
        };
    });

    return (
        <div className="w-full overflow-x-auto">
            <Table columns={columns} data={formattedData} />
        </div>
    );
}
